config/routes.rb
InsalesApp::Application.routes.draw do
  root to: 'main#index'

  resource  :session do
    collection do
      get :autologin
    end
  end

  get '/install',   to: 'insales_app#install',   as: :install
  get '/uninstall', to: 'insales_app#uninstall', as: :uninstall
  get '/login',     to: 'sessions#new',          as: :login
  get '/main',      to: 'main#index',            as: :main

  get ':controller/:action/:id'
  get ':controller/:action/:id.:format'
end

app/models/account.rb
class Account < ActiveRecord::Base
  validates_presence_of :insales_id
  validates_presence_of :insales_subdomain
  validates_presence_of :password
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details
  before_filter :authentication, :configure_api

  protected

  def authentication
    logout if enter_from_different_shop?

    if current_app and current_app.authorized?
      return if @account = Account.find_by(insales_subdomain: current_app.shop)
    end

    store_location

    if account_by_params
      init_authorization account_by_params
    else
      redirect_to login_path
    end
  end

  def logout
    reset_session
  end

  def configure_api
    current_app.configure_api
  end

  def init_authorization account
    session[:app] = MyApp.new(account.insales_subdomain, account.password)

    redirect_to session[:app].authorization_url
  end

  def store_location(path = nil)
    session[:return_to] = path || request.fullpath
  end

  def location
    session[:return_to]
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def enter_from_different_shop?
    current_app and !params[:shop].blank? && params[:shop] != current_app.shop
  end

  def account_by_params
    @account ||= if params[:insales_id]
      Account.find_by insales_id: params[:insales_id]
    else
      Account.find_by insales_subdomain: params[:shop]
    end
  end

  def current_app
    session[:app]
  end
end

app/controllers/insales_app_controller.rb
class InsalesAppController < ApplicationController
  skip_before_filter :authentication
  skip_before_filter :configure_api

  def install
    raise "Fail to install" unless MyApp.install params[:shop], params[:token], params[:insales_id]
    head :ok
  end

  def uninstall
    raise "Fail to uninstall" unless MyApp.uninstall params[:shop], params[:token]
    head :ok
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authentication, :configure_api, :except => [:destroy]
  layout 'login'

  def show
    render :action => :new
  end

  def create
    @shop = params[:shop]

    if account_by_params
      init_authorization account_by_params
    else
      flash.now[:error] = "Убедитесь, что адрес магазина указан правильно."
      render :action => :new
    end
  end

  def autologin
    if current_app and current_app.authorize params[:token]
      redirect_to location || root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    message_divs = []
    [:error, :notice].each do |key|
      next unless massage = flash[key]
      message_p = content_tag(:p, massage, :class => key)
      message_divs << content_tag(:div, message_p, :class=>"message")
    end
    flash.clear # Защита для того, чтобы не вывести flash дважды
    content_tag :div, message_divs.join(''), {:id => "flash_messages"}, false
  end

  def home_path
    "http://#{account_domain}/admin/home"
  end

  def account_domain
    session[:shop] || @account.insales_subdomain
  end

  def app_name
    'Мое приложение'
  end
end

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    = csrf_meta_tags
    %link{:href => "/assets/favicon.ico", :rel => "shortcut icon"}/
    %title #{app_name}
    = javascript_include_tag "application"
    = stylesheet_link_tag "application"

  %body
    .containerPage
      .head
        .headTop
          .leftHead
            %h1 #{app_name}
          .rightHead
            %p
              = link_to "Техподдержка", "http://#{@account.insales_subdomain}/admin/support"
              = image_tag 'techsupport_ico.gif'
              |
              \#{link_to 'Форум', 'http://forum.insales.ru', :target => '_blank'}
              |
              \#{link_to 'Выйти', session_path, :method => 'delete'}
        .leftTabs
          .Tab
            .tabLeftCorner
            .tabContent= link_to image_tag('home_inactive_icon.png', :title => 'Вернуться в магазин', :alt => 'Вернуться в магазин'), home_path
            .tabRightCorner
          .activeTab
            .tabLeftCorner
            .tabContent= link_to app_name, root_path
            .tabRightCorner
      .content
        %h1
          = link_to(image_tag('back_ico.png', :style => "margin-bottom:-5px", :alt => "На предыдущую страницу", :title => "На предыдущую страницу"), @back) if @back
        #page_title{:style => "display:inline;"}= @title
        </h1>
        - if @links
          #subtitle_links= @links
        = flash_messages
        = yield
      .footer
        %div
          %p
            \&copy;
            = succeed "," do
              %span{:style => "color: #752F16; font-weight: bold;"} InSales
            2010. &nbsp;|&nbsp;
            %a{:href => "http://www.insales.ru/terms"} Условия предоставления услуг

app/views/layouts/login.html.haml
%html
  %head
    %title
      InSales.ru &mdash; #{@title}
    = stylesheet_link_tag 'login'
    %link{:href => "/assets/favicon.ico", :rel => "shortcut icon"}/
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "content-type"}/
  %body
    .body
      .main
        %h1= @title
        = flash_messages
        = yield

app/views/main/index.html.haml
Hello